# -*- coding: utf-8 -*-
"""BigDataProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1942EpgdBLsB4ydhS7pKU1QKLykfDD2zS
"""

!sudo apt-get install -y fonts-nanum
!fc-cache -fv
import matplotlib.font_manager as fm
import matplotlib.pyplot as plt

plt.rc('font', family='NanumGothic')
plt.rc('axes', unicode_minus=False)

!pip install xgboost

import pandas as pd
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from xgboost import XGBRegressor
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

from google.colab import drive

drive.mount('/content/gdrive/')

file_path = '/content/gdrive/MyDrive/빅데이터/과제/final_emp_financial.csv'

df_original = pd.read_csv(file_path)

print(df_original.info())

numeric_cols = df_original.select_dtypes(include=['int64', 'float64']).columns
df_original[numeric_cols].describe()

df_original['보고서유형코드'] = df_original['보고서유형'].map({'반기보고서': 0, '사업보고서': 1})
df_original = df_original.sort_values(["기업명", "연도", "보고서유형코드"]).reset_index(drop=True)

font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
fm.fontManager.addfont(font_path)
plt.rc('font', family='NanumGothic')

plt.figure(figsize=(10,8))
sns.heatmap(df_original[numeric_cols].corr(), annot=False, cmap="coolwarm")
plt.title("각 지표별 상관관계 히트맵")
plt.show()

# 고용구조와 매출액증감율의 관계 분석 및 회귀 모델링

features = [
    '평균급여증감율',
    '남성직원수증감율', '여성직원수증감율',
    '정규직수증감율', '계약직수증감율',
]

target = '매출액증감율'

df = df_original

# 결측치 제거
data = df[features + [target]].dropna()

# 학습 데이터셋 분할
from sklearn.model_selection import train_test_split

X = data[features]
y = data[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=True, random_state=42
)

# 랜덤 포레스트 회귀
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

model = RandomForestRegressor(n_estimators=300, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)

# 모델 성능 평가
mse = mean_squared_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MSE:", mse)
print("RMSE:", mse**0.5)
print("R²:", r2)

# importance 시각화
import numpy as np

importance = model.feature_importances_

plt.figure(figsize=(10,6))
plt.barh(features, importance)
plt.xlabel("Importance")
plt.title("매출액증감율에 대한 피처 중요도")
plt.show()

# 실제값 vs 예측값 시각화 (로그스케일)
plt.figure(figsize=(8, 8))
plt.scatter(np.log1p(y_test), np.log1p(pred), alpha=0.5)
plt.plot([np.log1p(y_test).min(), np.log1p(y_test).max()],
         [np.log1p(y_test).min(), np.log1p(y_test).max()],
         'r--', linewidth=2)

plt.xlabel("실제값")
plt.ylabel("예측값")
plt.title("실제값과 예측값 비교 (로그스케일)")
plt.grid(True)
plt.show()

# 고용구조와 영업이익의 관계 분석 xgboost

df = df_original

# 1. 매출액 / 평균급여 숫자 정제
for col in ['영업이익', '평균급여']:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^0-9]', '', regex=True)   # 숫자만 남기기
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')
# 로그 변환 가능하도록 양수만 남기기
df = df[(df['영업이익'] > 0) & (df['평균급여'] > 0)]

# 2. 사용할 변수
features = [
    '평균급여',
    '남성직원수', '여성직원수',
    '정규직수', '계약직수',
    '남성정규직수', '여성정규직수',
    '남성계약직수', '여성계약직수',
]

target = '영업이익'

# 3. 결측치 제거
data = df[features + [target]].dropna()

X = data[features]
y = data[target]

# 4. 로그 변환
y_log = np.log1p(y)  # log(1+y)


# 5. 학습 데이터 분리
X_train, X_test, y_train_log, y_test_log = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

# 6. XGBoost 회귀 모델 학습
model = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)
model.fit(X_train, y_train_log)

# 7. 예측 및 평가
pred_log = model.predict(X_test)
y_pred = np.expm1(pred_log)     # 예측 복원
y_test = np.expm1(y_test_log)   # 실제값 복원

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE :", mse)
print("RMSE:", rmse)
print("R² :", r2)

# 8. Feature Importance 시각화
importance = model.feature_importances_

plt.figure(figsize=(10,7))
plt.barh(features, importance)
plt.title("영업이익에 대한 피처 중요도")
plt.xlabel("Importance")
plt.show()

# 9. 실제값 vs 예측값 시각화 (로그스케일)
plt.figure(figsize=(8, 8))
plt.scatter(np.log1p(y_test), np.log1p(y_pred), alpha=0.5)
plt.plot([np.log1p(y_test).min(), np.log1p(y_test).max()],
         [np.log1p(y_test).min(), np.log1p(y_test).max()],
         'r--', linewidth=2)

plt.xlabel("실제값")
plt.ylabel("예측값")
plt.title("실제값과 예측값 비교 (로그스케일)")
plt.grid(True)
plt.show()

# 고용구조와 매출액의 관계 분석 xgboost

df = df_original

# 1. 매출액 / 평균급여 숫자 정제
for col in ['매출액', '평균급여']:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r'[^0-9]', '', regex=True)   # 숫자만 남기기
    )
    df[col] = pd.to_numeric(df[col], errors='coerce')

# 로그 변환 가능하도록 양수만 남기기
df = df[(df['매출액'] > 0) & (df['평균급여'] > 0)]

# 2. 사용할 변수
features = [
    '평균급여',
    '남성직원수', '여성직원수',
    '정규직수', '계약직수',
    '남성정규직수', '여성정규직수',
    '남성계약직수', '여성계약직수',
]

target = '매출액'

# 3. 결측치 제거
data = df[features + [target]].dropna()

X = data[features]
y = data[target]

# 4. 로그 변환
y_log = np.log1p(y)  # log(1+y)

# 5. 학습 데이터 분리
X_train, X_test, y_train_log, y_test_log = train_test_split(
    X, y_log, test_size=0.2, random_state=42
)

# 6. XGBoost 회귀 모델 학습
model = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)

model.fit(X_train, y_train_log)

# 7. 예측 및 평가
pred_log = model.predict(X_test)
y_pred = np.expm1(pred_log)     # 예측 복원
y_test = np.expm1(y_test_log)   # 실제값 복원

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MSE :", mse)
print("RMSE:", rmse)
print("R² :", r2)

# 8. Feature Importance 시각화
importance = model.feature_importances_

plt.figure(figsize=(10,7))
plt.barh(features, importance)
plt.title("매출액에 대한 피처 중요도")
plt.xlabel("Importance")
plt.show()

# 9. 실제값 vs 예측값 시각화 (로그스케일)
plt.figure(figsize=(8, 8))
plt.scatter(np.log1p(y_test), np.log1p(y_pred), alpha=0.5)
plt.plot([np.log1p(y_test).min(), np.log1p(y_test).max()],
         [np.log1p(y_test).min(), np.log1p(y_test).max()],
         'r--', linewidth=2)

plt.xlabel("실제값")
plt.ylabel("예측값")
plt.title("실제값과 예측값 비교 (로그스케일)")
plt.grid(True)
plt.show()